// IFCExporter.idl : IDL source for IFCExporter
//

// This file will be processed by the MIDL tool to
// produce the type library (IFCExporter.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(28358790-DB13-40D1-B3C0-20D4E3A50E8B),
	version(1.0),
]
library IFCExporterLib
{
	importlib("stdole2.tlb");
};

